# -*- coding: utf-8 -*-
"""Barwon cleaned csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZ8m5SKK4ML7uWD_cJlhEcMMYA6MxLZA
"""

import pandas as pd


df = pd.read_csv("Barwon_Cleaned.csv")


df = df.rename(columns={
    "Site ID": "site_id",
    "Name": "source_name",
    "Datetime": "measurement_datetime"
})


final_df = df.pivot_table(
    index=["site_id", "source_name", "measurement_datetime"],
    columns="Parameter",
    values="Value",
    aggfunc="first"
).reset_index()


final_df.columns.name = None


final_df = final_df.rename(columns={
    "pH": "PH Value(PH)",
    "Turbidity": "Turbidity(NTU)",
    "Water Temperature": "Water Temperature(C)",
    "Nitrogen as NOx": "Nitrogen as NOx(mg/L)",
    "Total Suspended Solids (TSS)": "TSS(mg/L)",
    "Colour (True Filtered) (PCU)": "Colour(PCU)"
})


required_columns = [
    "site_id",
    "source_name",
    "measurement_datetime",
    "PH Value(PH)",
    "Turbidity(NTU)",
    "Water Temperature(C)",
    "Nitrogen as NOx(mg/L)",
    "TSS(mg/L)",
    "Colour(PCU)"
]


for col in required_columns:
    if col not in final_df.columns:
        final_df[col] = None

final_df = final_df[required_columns]


final_df.to_csv("Barwon_Final.csv", index=False)

print(final_df.head())

from google.colab import files


files.download("Barwon_Final.csv")

























