CREATE TABLE public."Final_Data" (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    capacity_ml NUMERIC(14, 2),
    measurement_datetime TEXT NOT NULL,
    cost_per_ml NUMERIC(14, 4),
    ph NUMERIC(5, 2),
    alkalinity NUMERIC(12, 3),
    turbidity NUMERIC(12, 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT sources_pkey
        PRIMARY KEY (record_id),
    CONSTRAINT unique_source_measurement
        UNIQUE (source_id, measurement_datetime),
    CONSTRAINT sources_capacity_nonnegative
        CHECK (capacity_ml IS NULL OR capacity_ml >= 0),
    CONSTRAINT sources_cost_nonnegative
        CHECK (cost_per_ml IS NULL OR cost_per_ml >= 0),
    CONSTRAINT sources_alkalinity_nonnegative
        CHECK (alkalinity IS NULL OR alkalinity >= 0),
    CONSTRAINT sources_turbidity_nonnegative
        CHECK (turbidity IS NULL OR turbidity >= 0),
    CONSTRAINT sources_valid_ph
        CHECK (ph IS NULL OR (ph >= 0 AND ph <= 14))
);