# -*- coding: utf-8 -*-
"""Thomson .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187jhw_aVWzpXR8G5BrIYcvop1KVdWQe3
"""

import pandas as pd

thomson = pd.read_csv("Thomson.csv", encoding="latin1")
barwon = pd.read_csv("Barwon.csv", encoding="latin1")

thomson.info()
barwon.info()

print(thomson.duplicated().sum())
print(barwon.duplicated().sum())

thomson = thomson.drop_duplicates()
barwon = barwon.drop_duplicates()

thomson["Datetime"] = pd.to_datetime(thomson["Datetime"])

barwon["Datetime"] = pd.to_datetime(barwon["Datetime"])

print(thomson.isnull().sum())

print(barwon.isnull().sum())

print(thomson.isnull().sum())

print(barwon.isnull().sum())

thomson.drop(columns=["Comment"], inplace=True)

barwon.drop(columns=["Comment"], inplace=True)

thomson["Qualifier"] = thomson["Qualifier"].fillna("None")

barwon["Qualifier"] = barwon["Qualifier"].fillna("None")

print(thomson.dtypes)

print(barwon.dtypes)

print(thomson["Value"].describe())

print(barwon["Value"].describe())

thomson = thomson[thomson["Value"] >= 0]

barwon = barwon[barwon["Value"] >= 0]

thomson = thomson.sort_values("Datetime")

barwon = barwon.sort_values("Datetime")

thomson.reset_index(drop=True, inplace=True)

barwon.reset_index(drop=True, inplace=True)

thomson.to_csv("Thomson_Cleaned.csv", index=False)

barwon.to_csv("Barwon_Cleaned.csv", index=False)

# Save the cleaned files
thomson.to_csv("Thomson_Cleaned.csv", index=False)
barwon.to_csv("Barwon_Cleaned.csv", index=False)

# Download them
from google.colab import files

files.download("Thomson_Cleaned.csv")
files.download("Barwon_Cleaned.csv")

