# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUZfMLGOkNJtWVO3WTqtcRiBugbkOcHV
"""

import pandas as pd
import numpy as np


file_path = "Thomson_reservoir.csv"

df = pd.read_csv(file_path, encoding="cp1252")

print("Dataset loaded successfully")
print("Rows:", len(df))
print("Columns:", len(df.columns))



print("\nColumn Names:")
print(df.columns.tolist())


print("\nMissing Values:")
print(df.isnull().sum())



duplicates = df.duplicated().sum()

print("\nDuplicate Records:", duplicates)



df["Datetime"] = pd.to_datetime(
    df["Datetime"],
    errors="coerce"
)

invalid_dates = df["Datetime"].isnull().sum()

print("\nInvalid Date/Time Records:", invalid_dates)



df["Value"] = pd.to_numeric(
    df["Value"],
    errors="coerce"
)

invalid_values = df["Value"].isnull().sum()

print("\nInvalid Numeric Values:", invalid_values)



negative_values = (df["Value"] < 0).sum()

print("\nNegative Values:", negative_values)



print("\nQuality Value Counts:")
print(df["Quality"].value_counts(dropna=False))



print("\nWater Quality Parameters:")
print(df["Parameter"].value_counts())



print("\nUnits used for each parameter:")

unit_check = (
    df.groupby("Parameter")["Unit of Measurement"]
    .unique()
)

print(unit_check)


Q1 = df["Value"].quantile(0.25)
Q3 = df["Value"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Value"] < lower_limit) |
    (df["Value"] > upper_limit)
]

print("\nNumber of Statistical Outliers:", len(outliers))

print("\nOutlier Records:")
print(outliers[
    ["Datetime", "Parameter", "Value", "Unit of Measurement"]
].head(20))



ph_data = df[
    df["Parameter"].str.contains(
        "pH",
        case=False,
        na=False
    )
]

invalid_ph = ph_data[
    (ph_data["Value"] < 0) |
    (ph_data["Value"] > 14)
]

print("\nInvalid pH Records:", len(invalid_ph))

if len(invalid_ph) > 0:
    print(invalid_ph[
        ["Datetime", "Parameter", "Value"]
    ])



validation_summary = {
    "Total Records": len(df),
    "Total Columns": len(df.columns),
    "Missing Values": int(df.isnull().sum().sum()),
    "Duplicate Records": int(duplicates),
    "Invalid Dates": int(invalid_dates),
    "Invalid Numeric Values": int(invalid_values),
    "Negative Values": int(negative_values),
    "Statistical Outliers": int(len(outliers)),
    "Invalid pH Values": int(len(invalid_ph))
}

print("\n==============================")
print("DATA VALIDATION SUMMARY")
print("==============================")

for key, value in validation_summary.items():
    print(f"{key}: {value}")



df.to_csv(
    "Thomson_reservoir_validated.csv",
    index=False
)

print("\nValidated dataset saved as:")
print("Thomson_reservoir_validated.csv")